### ISSUE TITLE
Make an API Platform cloud instance available to the team 

### ISSUE THREAD

**Issue by lucasjellema** [lucasjellema/soaring-through-the-cloud-native-sequel#2]
Arrange an API Platform cloud instance that the team can use to define policies and routing for APIs and that allows us to consume APIs from a central provider.

**Comment by luisw19** [comment]
@lucasjellema @svenbernhardt I have an API instance on my OACED account that we can use. I have full control so we can do anything we want. Perhaps we can use it? also still have cloud credits available so happy to use them as well.

**Comment by lucasjellema** [comment]
Hi Luis, great if we can use your API instance!
Can you create user accounts for all of us or share (through a secure channel) your credentials for this environment?
Lucas

**Comment by luisw19** [comment]
Already did :)

**Comment by lucasjellema** [comment]
Is this issue then still open ? Or can it be closed?

**Comment by luisw19** [comment]
@lucasjellema closed!
