### ISSUE TITLE
Provide guidelines for using Apiary on defining and designing APIs

### ISSUE THREAD

**Issue by lucasjellema** [lucasjellema/soaring-through-the-cloud-native-sequel#3]
We want to describe the APIs of our microservices using Apiary.  However, which Apiary environment can we use?  Should we work in a shared Apiary environment – with multiple projects for example? Can you help us with setting up an environment?

**Comment by ldikmans** [comment]
to work with multiple people on it, you need a team license. You can only be part of one team at the moment. I am already part of a team, so I can't join another. (Last time I checked this with PM was in December 2017).
WE could however all have our own account and create an API and give it to someone who does not have team account yet? Then we can publish it in the API Platform developer portal. Alternatively we create swaggers with Apiary and everyone imports it in their own environment by getting it from git.

What do you think @luisw19 ?

**Comment by luisw19** [comment]
@ldikmans yes, it's probably the quickest way. Then we can manually create the blueprint files into the git repository. This will be required in order to run dredd as part of the CICD process (assuming based on wercker)

@lucasjellema I've have a chapter on our coming book covering API design best practices and guidence. Rather than "re-inventing the wheel" would be happy to share the chapter to the group in confidence? (given that book is not published yet?) the chapter describes in great degree of detail API-design first process.

**Comment by ldikmans** [comment]
That would be awesome Luis!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by lucasjellema** [comment]
It would be great if you would share that chapter Luis!

So we will each create the API definitions - should this be BluePrint or OpenAPI? - (ideally using our personal Apiary instance), and add the resulting artifacts to GitHub. That makes sense. However: to our own microservice specific repository - or to a central repo that contains all microservices?

Is there a direct link from Apiary to API Platform?

**Comment by luisw19** [comment]
@lucasjellema I honestly prefer more API Blueprint. In fact, from my experience clients like it more (however this is very subjective and some might prefer OpenAPI/Swagger). API Blueprint because of Markdown notation it's easier.

@lucasjellema should I share the chapter through Slack?

**Comment by lucasjellema** [comment]
@luisw19 if you can provide your chapter on Slack, that would we great.
Regarding API format - I think with Apiary, we can switch at any time between OpenAPI and Blueprint - is that correct?
One advantage of OpenAPI/Swagger is that VBCS understands that definition - while it does not know Blueprint.

**Comment by luisw19** [comment]
@lucasjellema you can choose which format to use prior creating the API definition, but I dont think you can switch once you select a format. However I've been using Apiamatic API Transformer  (https://apimatic.io/transformer) and it does excellent conversions. Also have already uploaded the chapter so will close this issue :)
